:hammer: Fixed -Werror=range-loop-construct in PrecalParser.cpp
See https://github.com/Gjacquenot/test_ubuntu22/runs/6546191019?check_suite_focus=true

/opt/share/code/hdb_interpolators/src/PrecalParser.cpp: In member function 'std::vector<double> PrecalParser::get_vector_value(const string&, const string&, const string&, const string&) const':
/opt/share/code/hdb_interpolators/src/PrecalParser.cpp:105:33: error: loop variable 'kv' creates a copy from type 'const std::pair<const std::__cxx11::basic_string<char>, std::vector<double> >' [-Werror=range-loop-construct]
  105 |                 for (const auto kv : section.vector_values)
      |                                 ^~
compilation terminated due to -Wfatal-errors.