:hammer: Fixed a include conflict with googletest 1.11.0 and boost 1.60.0 with ubuntu 22.04 and g++ 11.2
Boost made a suggestion

If you want to output boost::optional, include header <boost/optional/optional_io.hpp>

FAILED: yaml_parser/unit_tests/CMakeFiles/yaml_parser_tests.dir/src/environment_parsersTest.cpp.o
/usr/bin/c++ -DEIGEN_DISABLE_UNALIGNED_ARRAY_ASSERT -DEIGEN_DONT_VECTORIZE -DGTEST_HAS_POSIX_RE=0 -I/opt/share/build_deb11 -I/opt/share/code/yaml_parser/inc -I/opt/share/code/ssc -I/opt/share/code/exceptions/inc -I/opt/share/code/external_data_structures/inc -I/opt/share/code/environment_models/inc -I/opt/share/code/yaml_parser/.. -I/opt/share/code/yaml_parser/unit_tests/inc -I/opt/share/code/test_data_generator/inc -isystem /opt/share/code/yaml-cpp/src -isystem /opt/share/code/yaml-cpp/include -isystem /opt/share/code/yaml-cpp/include/yaml-cpp -isystem /opt/boost/include -isystem /opt/googletest/googletest/include -isystem /opt/googletest/googletest/include/gtest -isystem /opt/googletest/googlemock/include -isystem /opt/googletest/googlemock/include/gmock -Werror -pedantic -pedantic-errors -Wextra -Wall -Wunused-function -Wunused-label -Wunused-parameter -Wunused-value -Wunused-variable -fno-common -Wformat=2 -Winit-self -Wpacked -Wpointer-arith -Wmissing-declarations -Wmissing-format-attribute -Wsign-compare -Wstrict-aliasing=2 -Wundef -Wconversion -Wno-misleading-indentation -Woverloaded-virtual -Weffc++ -Wwrite-strings -Wfatal-errors -Wno-deprecated -Wvariadic-macros -std=gnu++11 -fPIC -O3 -std=gnu++0x -O3 -DNDEBUG -MD -MT yaml_parser/unit_tests/CMakeFiles/yaml_parser_tests.dir/src/environment_parsersTest.cpp.o -MF yaml_parser/unit_tests/CMakeFiles/yaml_parser_tests.dir/src/environment_parsersTest.cpp.o.d -o yaml_parser/unit_tests/CMakeFiles/yaml_parser_tests.dir/src/environment_parsersTest.cpp.o -c /opt/share/code/yaml_parser/unit_tests/src/environment_parsersTest.cpp
In file included from /opt/boost/include/boost/optional/optional.hpp:30,
                 from /opt/boost/include/boost/optional.hpp:15,
                 from /opt/share/code/yaml_parser/inc/environment_parsers.hpp:16,
                 from /opt/share/code/yaml_parser/unit_tests/src/environment_parsersTest.cpp:9:
/opt/boost/include/boost/optional/optional.hpp: In instantiation of 'std::basic_ostream<_Ch, _Tr>& boost::operator<<(std::basic_ostream<_Ch, _Tr>&, const boost::optional_detail::optional_tag&) [with CharType = char; CharTrait = std::char_traits<char>]':
/opt/googletest/googletest/include/gtest/gtest-printers.h:215:9:   required from 'static void testing::internal::internal_stream_operator_without_lexical_name_lookup::StreamPrinter::PrintValue(const T&, std::ostream*) [with T = boost::optional<int>; <template-parameter-1-2> = void; <template-parameter-1-3> = std::basic_ostream<char>&; std::ostream = std::basic_ostream<char>]'
/opt/googletest/googletest/include/gtest/gtest-printers.h:312:22:   required from 'void testing::internal::PrintWithFallback(const T&, std::ostream*) [with T = boost::optional<int>; std::ostream = std::basic_ostream<char>]'
/opt/googletest/googletest/include/gtest/gtest-printers.h:441:30:   required from 'void testing::internal::PrintTo(const T&, std::ostream*) [with T = boost::optional<int>; std::ostream = std::basic_ostream<char>]'
/opt/googletest/googletest/include/gtest/gtest-printers.h:691:12:   required from 'static void testing::internal::UniversalPrinter<T>::Print(const T&, std::ostream*) [with T = boost::optional<int>; std::ostream = std::basic_ostream<char>]'
/opt/googletest/googletest/include/gtest/gtest-printers.h:980:30:   required from 'void testing::internal::UniversalPrint(const T&, std::ostream*) [with T = boost::optional<int>; std::ostream = std::basic_ostream<char>]'
/opt/googletest/googletest/include/gtest/gtest-printers.h:865:19:   [ skipping 2 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
/opt/googletest/googletest/include/gtest/gtest-printers.h:334:36:   required from 'static std::string testing::internal::FormatForComparison<ToPrint, OtherOperand>::Format(const ToPrint&) [with ToPrint = boost::optional<int>; OtherOperand = int; std::string = std::__cxx11::basic_string<char>]'
/opt/googletest/googletest/include/gtest/gtest-printers.h:415:45:   required from 'std::string testing::internal::FormatForComparisonFailureMessage(const T1&, const T2&) [with T1 = boost::optional<int>; T2 = int; std::string = std::__cxx11::basic_string<char>]'
/opt/googletest/googletest/include/gtest/gtest.h:1528:53:   required from 'testing::AssertionResult testing::internal::CmpHelperEQFailure(const char*, const char*, const T1&, const T2&) [with T1 = int; T2 = boost::optional<int>]'
/opt/googletest/googletest/include/gtest/gtest.h:1549:28:   required from 'testing::AssertionResult testing::internal::CmpHelperEQ(const char*, const char*, const T1&, const T2&) [with T1 = int; T2 = boost::optional<int>]'
/opt/googletest/googletest/include/gtest/gtest.h:1564:23:   required from 'static testing::AssertionResult testing::internal::EqHelper::Compare(const char*, const char*, const T1&, const T2&) [with T1 = int; T2 = boost::optional<int>; typename std::enable_if<((! std::is_integral<_Tp>::value) || (! std::is_pointer<_Dp>::value))>::type* <anonymous> = 0]'
/opt/share/code/yaml_parser/unit_tests/src/environment_parsersTest.cpp:181:5:   required from here
/opt/boost/include/boost/optional/optional.hpp:1276:3: error: static assertion failed: If you want to output boost::optional, include header <boost/optional/optional_io.hpp>
 1276 |   BOOST_STATIC_ASSERT_MSG(sizeof(CharType) == 0, "If you want to output boost::optional, include header <boost/optional/optional_io.hpp>");
      |   ^~~~~~~~~~~~~~~~~~~~~~~
:hammer: Fixed a include conflict with googletest 1.11.0 and boost 1.60.0 with ubuntu 22.04 and g++ 11.2

Boost made a suggestion

If you want to output boost::optional, include header <boost/optional/optional_io.hpp>

FAILED: yaml_parser/unit_tests/CMakeFiles/yaml_parser_tests.dir/src/environment_parsersTest.cpp.o
/usr/bin/c++ -DEIGEN_DISABLE_UNALIGNED_ARRAY_ASSERT -DEIGEN_DONT_VECTORIZE -DGTEST_HAS_POSIX_RE=0 -I/opt/share/build_deb11 -I/opt/share/code/yaml_parser/inc -I/opt/share/code/ssc -I/opt/share/code/exceptions/inc -I/opt/share/code/external_data_structures/inc -I/opt/share/code/environment_models/inc -I/opt/share/code/yaml_parser/.. -I/opt/share/code/yaml_parser/unit_tests/inc -I/opt/share/code/test_data_generator/inc -isystem /opt/share/code/yaml-cpp/src -isystem /opt/share/code/yaml-cpp/include -isystem /opt/share/code/yaml-cpp/include/yaml-cpp -isystem /opt/boost/include -isystem /opt/googletest/googletest/include -isystem /opt/googletest/googletest/include/gtest -isystem /opt/googletest/googlemock/include -isystem /opt/googletest/googlemock/include/gmock -Werror -pedantic -pedantic-errors -Wextra -Wall -Wunused-function -Wunused-label -Wunused-parameter -Wunused-value -Wunused-variable -fno-common -Wformat=2 -Winit-self -Wpacked -Wpointer-arith -Wmissing-declarations -Wmissing-format-attribute -Wsign-compare -Wstrict-aliasing=2 -Wundef -Wconversion -Wno-misleading-indentation -Woverloaded-virtual -Weffc++ -Wwrite-strings -Wfatal-errors -Wno-deprecated -Wvariadic-macros -std=gnu++11 -fPIC -O3 -std=gnu++0x -O3 -DNDEBUG -MD -MT yaml_parser/unit_tests/CMakeFiles/yaml_parser_tests.dir/src/environment_parsersTest.cpp.o -MF yaml_parser/unit_tests/CMakeFiles/yaml_parser_tests.dir/src/environment_parsersTest.cpp.o.d -o yaml_parser/unit_tests/CMakeFiles/yaml_parser_tests.dir/src/environment_parsersTest.cpp.o -c /opt/share/code/yaml_parser/unit_tests/src/environment_parsersTest.cpp
In file included from /opt/boost/include/boost/optional/optional.hpp:30,
                 from /opt/boost/include/boost/optional.hpp:15,
                 from /opt/share/code/yaml_parser/inc/environment_parsers.hpp:16,
                 from /opt/share/code/yaml_parser/unit_tests/src/environment_parsersTest.cpp:9:
/opt/boost/include/boost/optional/optional.hpp: In instantiation of 'std::basic_ostream<_Ch, _Tr>& boost::operator<<(std::basic_ostream<_Ch, _Tr>&, const boost::optional_detail::optional_tag&) [with CharType = char; CharTrait = std::char_traits<char>]':
/opt/googletest/googletest/include/gtest/gtest-printers.h:215:9:   required from 'static void testing::internal::internal_stream_operator_without_lexical_name_lookup::StreamPrinter::PrintValue(const T&, std::ostream*) [with T = boost::optional<int>; <template-parameter-1-2> = void; <template-parameter-1-3> = std::basic_ostream<char>&; std::ostream = std::basic_ostream<char>]'
/opt/googletest/googletest/include/gtest/gtest-printers.h:312:22:   required from 'void testing::internal::PrintWithFallback(const T&, std::ostream*) [with T = boost::optional<int>; std::ostream = std::basic_ostream<char>]'
/opt/googletest/googletest/include/gtest/gtest-printers.h:441:30:   required from 'void testing::internal::PrintTo(const T&, std::ostream*) [with T = boost::optional<int>; std::ostream = std::basic_ostream<char>]'
/opt/googletest/googletest/include/gtest/gtest-printers.h:691:12:   required from 'static void testing::internal::UniversalPrinter<T>::Print(const T&, std::ostream*) [with T = boost::optional<int>; std::ostream = std::basic_ostream<char>]'
/opt/googletest/googletest/include/gtest/gtest-printers.h:980:30:   required from 'void testing::internal::UniversalPrint(const T&, std::ostream*) [with T = boost::optional<int>; std::ostream = std::basic_ostream<char>]'
/opt/googletest/googletest/include/gtest/gtest-printers.h:865:19:   [ skipping 2 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
/opt/googletest/googletest/include/gtest/gtest-printers.h:334:36:   required from 'static std::string testing::internal::FormatForComparison<ToPrint, OtherOperand>::Format(const ToPrint&) [with ToPrint = boost::optional<int>; OtherOperand = int; std::string = std::__cxx11::basic_string<char>]'
/opt/googletest/googletest/include/gtest/gtest-printers.h:415:45:   required from 'std::string testing::internal::FormatForComparisonFailureMessage(const T1&, const T2&) [with T1 = boost::optional<int>; T2 = int; std::string = std::__cxx11::basic_string<char>]'
/opt/googletest/googletest/include/gtest/gtest.h:1528:53:   required from 'testing::AssertionResult testing::internal::CmpHelperEQFailure(const char*, const char*, const T1&, const T2&) [with T1 = int; T2 = boost::optional<int>]'
/opt/googletest/googletest/include/gtest/gtest.h:1549:28:   required from 'testing::AssertionResult testing::internal::CmpHelperEQ(const char*, const char*, const T1&, const T2&) [with T1 = int; T2 = boost::optional<int>]'
/opt/googletest/googletest/include/gtest/gtest.h:1564:23:   required from 'static testing::AssertionResult testing::internal::EqHelper::Compare(const char*, const char*, const T1&, const T2&) [with T1 = int; T2 = boost::optional<int>; typename std::enable_if<((! std::is_integral<_Tp>::value) || (! std::is_pointer<_Dp>::value))>::type* <anonymous> = 0]'
/opt/share/code/yaml_parser/unit_tests/src/environment_parsersTest.cpp:181:5:   required from here
/opt/boost/include/boost/optional/optional.hpp:1276:3: error: static assertion failed: If you want to output boost::optional, include header <boost/optional/optional_io.hpp>
 1276 |   BOOST_STATIC_ASSERT_MSG(sizeof(CharType) == 0, "If you want to output boost::optional, include header <boost/optional/optional_io.hpp>");
      |   ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.