:hammer: Fixed -Werror=range-loop-construct in MeshIntersector.cpp
See https://github.com/Gjacquenot/test_ubuntu22/runs/6545024896?check_suite_focus=true#step:4:2364

/opt/share/code/mesh/src/MeshIntersector.cpp: In member function 'void MeshIntersector::build_closing_edge()':
2366
/opt/share/code/mesh/src/MeshIntersector.cpp:149:21: error: loop variable 'l' creates a copy from type 'const std::vector<long unsigned int>' [-Werror=range-loop-construct]
2367
  149 |     for (const auto l:ll)
2368
      |                     ^
2369
compilation terminated due to -Wfatal-errors.
2370
cc1plus: all warnings being treated as errors