:hammer: Fixed -Werror=range-loop-construct in AiryTest.cpp
See https://github.com/Gjacquenot/test_ubuntu22/runs/6546115356?check_suite_focus=true#step:5:2498

/opt/share/code/environment_models/unit_tests/src/AiryTest.cpp:96:21: error: loop variable 'phase' creates a copy from type 'const std::vector<double>' [-Werror=range-loop-construct]
2498
   96 |     for (const auto phase:serialized_spectrum.phase)
2499
      |                     ^~~~~
2500
compilation terminated due to -Wfatal-errors.
2501
cc1plus: all warnings being treated as errors
2502