:hammer: Added missing override keyword for is_a_surface_force_model
https://github.com/Gjacquenot/test_clang/runs/7686247864?check_suite_focus=true#step:5:3671

[522/908] Building CXX object core/CMakeFiles/core.dir/src/ImmersedSurfaceForceModel.cpp.o
FAILED: core/CMakeFiles/core.dir/src/ImmersedSurfaceForceModel.cpp.o
/usr/bin/clang++ -DGTEST_HAS_POSIX_RE=0 -I. -I/opt/share/code/core/inc -I/opt/share/code/ssc -I/opt/share/code/exceptions/inc -I/opt/share/code/external_data_structures/inc -I/opt/share/code/external_file_formats/inc -I/opt/share/code/yaml_parser/inc -I/opt/share/code/environment_models/inc -I/opt/share/code/mesh/inc -I/opt/share/code/hdb_interpolators/inc -isystem /opt/boost/include -isystem /opt/eigen -isystem /opt/share/code/yaml-cpp/src -isystem /opt/share/code/yaml-cpp/include -isystem /opt/share/code/yaml-cpp/include/yaml-cpp -Werror -pedantic -pedantic-errors -Wextra -Wall -Wunused-function -Wunused-label -Wunused-parameter -Wunused-value -Wunused-variable -fno-common -Wformat=2 -Winit-self -Wpacked -Wpointer-arith -Wmissing-declarations -Wmissing-format-attribute -Wsign-compare -Wstrict-aliasing=2 -Wundef -Wconversion -Wno-misleading-indentation -Woverloaded-virtual -Weffc++ -Wwrite-strings -Wfatal-errors -Wno-deprecated -Wvariadic-macros -fPIC -std=gnu++11 -std=gnu++0x -O3 -DNDEBUG -MD -MT core/CMakeFiles/core.dir/src/ImmersedSurfaceForceModel.cpp.o -MF core/CMakeFiles/core.dir/src/ImmersedSurfaceForceModel.cpp.o.d -o core/CMakeFiles/core.dir/src/ImmersedSurfaceForceModel.cpp.o -c /opt/share/code/core/src/ImmersedSurfaceForceModel.cpp
In file included from /opt/share/code/core/src/ImmersedSurfaceForceModel.cpp:8:
In file included from /opt/share/code/core/inc/ImmersedSurfaceForceModel.hpp:11:
/opt/share/code/core/inc/SurfaceForceModel.hpp:80:14: fatal error: 'is_a_surface_force_model' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
        bool is_a_surface_force_model() const;
             ^
/opt/share/code/core/inc/ForceModel.hpp:89:22: note: overridden virtual function is here
        virtual bool is_a_surface_force_model() const;
                     ^
1 error generated.

[523/908] Building CXX object core/CMakeFiles/core.dir/src/SurfaceForceModel.cpp.o