:hammer: Explicitly defined default arguments to use C++ default constructor
Otherwise pybind11 gives a compilation error with flag -Weffc++

//g++ -isystem /usr/include/python3.7m main.cpp -c -Weffc++ -o main.o
 #include <pybind11/pybind11.h>
 #include <string>
namespace py = pybind11;
struct Input
{
    Input() = default;
    std::string name;
};

// The following code gives the following error message, due to -Weffc++ flag
PYBIND11_MODULE(example_ko, m) {
    py::class_<Input>(m, "Struct")
        .def(py::init<>());
}

// The following code works with -Weffc++ because we defined default constructor values
PYBIND11_MODULE(example_ok, m) {
    py::class_<Input>(m, "Struct")
        .def(py::init<const std::string&>(), py::arg("name") = "");
}

main.cpp: In instantiation of ‘Class* pybind11::detail::initimpl::construct_or_initialize(Args&& ...) [with Class = Input; Args = {}; typename std::enable_if<std::is_constructible<_Tp, _Args>::value, int>::type <anonymous> = 0]’:
/usr/include/pybind11/detail/init.h:174:66:   required from ‘static void pybind11::detail::initimpl::constructor<Args>::execute(Class&, const Extra& ...) [with Class = pybind11::class_<Input>; Extra = {}; typename std::enable_if<(! Class::has_alias), int>::type <anonymous> = 0; Args = {}]’
/usr/include/pybind11/pybind11.h:1115:9:   required from ‘pybind11::class_<type_, options>& pybind11::class_<type_, options>::def(const pybind11::detail::initimpl::constructor<Args ...>&, const Extra& ...) [with Args = {}; Extra = {}; type_ = Input; options = {}]’
main.cpp:20:26:   required from here
main.cpp:7:5: warning: ‘Input::name’ should be initialized in the member initialization list [-Weffc++]
     Input() = default;
     ^~~~~
In file included from /usr/include/pybind11/pybind11.h:46,
                 from main.cpp:2:
/usr/include/pybind11/detail/init.h:61:64: note: synthesized method ‘Input::Input()’ first required here
 inline Class *construct_or_initialize(Args &&...args) { return new Class(std::forward<Args>(args)...); }
                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~