:hammer: Fixed -Werror=range-loop-construct in 2DMeshDisplay.cpp
See https://github.com/Gjacquenot/test_ubuntu22/runs/6546081974?check_suite_focus=true#step:5:2436

/opt/share/code/mesh/src/2DMeshDisplay.cpp:103:21: error: loop variable 'edge' creates a copy from type 'const std::pair<long unsigned int, long unsigned int>' [-Werror=range-loop-construct]
2436
  103 |     for (const auto edge:mesh.edges)
2437
      |                     ^~~~
2438
compilation terminated due to -Wfatal-errors.
2439
cc1plus: all warnings being treated as errors