:hammer: Fixed -Werror=range-loop-construct in ClosingFacetComputer.cpp
See https://github.com/Gjacquenot/test_ubuntu22/runs/6545957068?check_suite_focus=true#step:5:2446


/opt/share/code/mesh/src/ClosingFacetComputer.cpp:128:21: error: loop variable 'edge' creates a copy from type 'const std::pair<long unsigned int, long unsigned int>' [-Werror=range-loop-construct]
2446
  128 |     for (const auto edge:edges_) add_edge(idx_in_mesh_to_node_idx[edge.first], idx_in_mesh_to_node_idx[edge.second], G);
2447
      |                     ^~~~
2448
compilation terminated due to -Wfatal-errors.
2449
cc1plus: all warnings being treated as errors