:hammer: Fixed -Werror=range-loop-construct in ClosingFacetComputer.cpp
See https://github.com/Gjacquenot/test_ubuntu22/runs/6545532126?check_suite_focus=true#step:5:2445

/opt/share/code/mesh/src/ClosingFacetComputer.cpp: In function 'std::vector<std::vector<long unsigned int> > convert_sets_to_vectors(const std::vector<std::set<long unsigned int> >&)':
2445
/opt/share/code/mesh/src/ClosingFacetComputer.cpp:105:21: error: loop variable 'facet' creates a copy from type 'const std::set<long unsigned int>' [-Werror=range-loop-construct]
2446
  105 |     for (const auto facet : facets)
2447
      |                     ^~~~~
2448
compilation terminated due to -Wfatal-errors.
2449
cc1plus: all warnings being treated as errors