:hammer: Removed unused captured parameters
See https://github.com/Gjacquenot/test_clang/runs/7867003389?check_suite_focus=true

[680/908] Building CXX object observers_and_api/unit_tests/CMakeFiles/observers_and_api_tests.dir/src/SimTest.cpp.o
FAILED: observers_and_api/unit_tests/CMakeFiles/observers_and_api_tests.dir/src/SimTest.cpp.o
/usr/bin/clang++ -DGTEST_HAS_POSIX_RE=0 -I. -I/opt/share/code/observers_and_api/inc -I/opt/share/code/exceptions/inc -I/opt/share/code/ssc -I/opt/share/code/interface_hdf5/inc -I/opt/share/code/external_data_structures/inc -I/opt/share/code/core/inc -I/opt/share/code/hdb_interpolators/inc -I/opt/share/code/force_models/inc -I/opt/share/code/mesh/inc -I/opt/share/code/yaml_parser/inc -I/opt/share/code/environment_models/inc -I/opt/share/code/external_file_formats/inc -I/opt/share/code/listeners_and_controllers/inc -I/opt/share/code/grpc/inc -I/opt/share/code/observers_and_api/unit_tests/inc -I/opt/share/code/test_data_generator/inc -I/opt/share/code/binary_stl_data/inc -isystem /usr/local/hdf5/include -isystem /opt/eigen -isystem /opt/eigen3-hdf5 -isystem /opt/boost/include -isystem /opt/share/code/base91x -isystem /opt/share/code/yaml-cpp/src -isystem /opt/share/code/yaml-cpp/include -isystem /opt/share/code/yaml-cpp/include/yaml-cpp -isystem /opt/grpc/include -isystem /opt/googletest/googletest/include -isystem /opt/googletest/googletest/include/gtest -Werror -pedantic -pedantic-errors -Wextra -Wall -Wunused-function -Wunused-label -Wunused-parameter -Wunused-value -Wunused-variable -fno-common -Wformat=2 -Winit-self -Wpacked -Wpointer-arith -Wmissing-declarations -Wmissing-format-attribute -Wsign-compare -Wstrict-aliasing=2 -Wundef -Wconversion -Wno-misleading-indentation -Woverloaded-virtual -Weffc++ -Wwrite-strings -Wfatal-errors -Wno-deprecated -Wvariadic-macros -fPIC -std=gnu++11 -std=gnu++0x -O3 -DNDEBUG -MD -MT observers_and_api/unit_tests/CMakeFiles/observers_and_api_tests.dir/src/SimTest.cpp.o -MF observers_and_api/unit_tests/CMakeFiles/observers_and_api_tests.dir/src/SimTest.cpp.o.d -o observers_and_api/unit_tests/CMakeFiles/observers_and_api_tests.dir/src/SimTest.cpp.o -c /opt/share/code/observers_and_api/unit_tests/src/SimTest.cpp
/opt/share/code/observers_and_api/unit_tests/src/SimTest.cpp:555:15: fatal error: lambda capture 'k' is not used [-Wunused-lambda-capture]
    auto z = [k,m,z0,w0,omega,zeq](const double t){return (z0-zeq)*cos(omega*t) + w0/omega*sin(omega*t) + zeq;};
              ^~
1 error generated.