:hammer: Fixed -Werror=range-loop-construct in PrecalParserHelper.cpp
/opt/share/code/hdb_interpolators/src/PrecalParserHelper.cpp:257:25: error: loop variable 'token' creates a copy from type 'const std::__cxx11::basic_string<char>' [-Werror=range-loop-construct]
  257 |         for (const auto token : tokens)
      |                         ^~~~~
compilation terminated due to -Wfatal-errors.
cc1plus: all warnings being treated as errors