:hammer: Told clang compiler to ignore C++17 generated code
protoc generates C++ 2017 code with [[nodiscard]] keyword

When specifying C++ 2011, the clang compiler emits a warning that is converted to an error

See https://clang.llvm.org/docs/DiagnosticsReference.html#wc-17-attribute-extensions

-Wc++17-attribute-extensions

Diagnostic text:

warning: use of the A attribute is a C++17 extension

[623/908] Building CXX object grpc/CMakeFiles/grpc.dir/wave_types.grpc.pb.cc.o
FAILED: grpc/CMakeFiles/grpc.dir/wave_types.grpc.pb.cc.o
/usr/bin/clang++ -DGTEST_HAS_POSIX_RE=0 -I. -I/opt/share/code/grpc/inc -I/opt/share/code/ssc -I/opt/share/code/exceptions/inc -I/opt/share/code/external_data_structures/inc -I/opt/share/code/core/inc -I/opt/share/code/environment_models/inc -I/opt/share/code/hdb_interpolators/inc -I/opt/share/code/mesh/inc -isystem /opt/eigen -isystem /opt/boost/include -isystem /opt/grpc/include -isystem grpc -isystem /opt/share/code/yaml-cpp/src -isystem /opt/share/code/yaml-cpp/include -isystem /opt/share/code/yaml-cpp/include/yaml-cpp -Werror -pedantic -pedantic-errors -Wextra -Wall -Wunused-function -Wunused-label -Wunused-parameter -Wunused-value -Wunused-variable -fno-common -Wformat=2 -Winit-self -Wpacked -Wpointer-arith -Wmissing-declarations -Wmissing-format-attribute -Wsign-compare -Wstrict-aliasing=2 -Wundef -Wconversion -Wno-misleading-indentation -Woverloaded-virtual -Weffc++ -Wwrite-strings -Wfatal-errors -Wno-deprecated -Wvariadic-macros -fPIC -std=gnu++11 -O3 -DNDEBUG -MD -MT grpc/CMakeFiles/grpc.dir/wave_types.grpc.pb.cc.o -MF grpc/CMakeFiles/grpc.dir/wave_types.grpc.pb.cc.o.d -o grpc/CMakeFiles/grpc.dir/wave_types.grpc.pb.cc.o -c grpc/wave_types.grpc.pb.cc
In file included from grpc/wave_types.grpc.pb.cc:5:
grpc/wave_types.pb.h:264:3: fatal error: use of the 'nodiscard' attribute is a C++17 extension [-Wc++17-attribute-extensions]
  PROTOBUF_NODISCARD std::string* release_parameters();
  ^
/opt/grpc/include/google/protobuf/port_def.inc:463:30: note: expanded from macro 'PROTOBUF_NODISCARD'
                             ^
1 error generated.
ninja: build stopped: subcommand failed.
make: *** [Makefile:62: build-debian-clang] Error 1