:hammer: Dealt with unused return value for listeners_and_controllers/src/TempFile.cpp
TempFile.cpp.o -c /opt/share/code/listeners_and_controllers/src/TempFile.cpp
/opt/share/code/listeners_and_controllers/src/TempFile.cpp: In function 'std::string get_temp_filename()':
/opt/share/code/listeners_and_controllers/src/TempFile.cpp:19:12: error: ignoring return value of 'int mkstemp(char*)' declared with attribute 'warn_unused_result' [-Werror=unused-result]
   19 |     mkstemp(filename);
      |     ~~~~~~~^~~~~~~~~~
compilation terminated due to -Wfatal-errors.
cc1plus: all warnings being treated as errors