:hammer: Fixed uninitialized members
/usr/bin/c++ -DGTEST_HAS_POSIX_RE=0 -I. -I/opt/share/code/external_data_structures -I/opt/share/code/external_file_formats -I/opt/share/code/ssc -I/opt/share/code/exceptions -isystem /opt/eigen -isystem /opt/boost/include -Werror -pedantic -pedantic-errors -Wextra -Wall -Wunused-function -Wunused-label -Wunused-parameter -Wunused-value -Wunused-variable -fno-common -Wformat=2 -Winit-self -Wpacked -Wpointer-arith -Wmissing-declarations -Wmissing-format-attribute -Wsign-compare -Wstrict-aliasing=2 -Wundef -Wconversion -Wno-misleading-indentation -Woverloaded-virtual -Weffc++ -Wwrite-strings -Wfatal-errors -Wno-deprecated -Wvariadic-macros -std=gnu++11 -fPIC -O3 -O3 -DNDEBUG -std=gnu++11 -MD -MT mesh/CMakeFiles/mesh.dir/MeshBuilder.cpp.o -MF mesh/CMakeFiles/mesh.dir/MeshBuilder.cpp.o.d -o mesh/CMakeFiles/mesh.dir/MeshBuilder.cpp.o -c /opt/share/code/mesh/MeshBuilder.cpp
/opt/share/code/mesh/MeshBuilder.cpp: In constructor 'MeshBuilder::MeshBuilder(const VectorOfVectorOfPoints&, bool)':
/opt/share/code/mesh/MeshBuilder.cpp:8:1: error: 'MeshBuilder::facetsPerEdge' should be initialized in the member initialization list [-Werror=effc++]
    8 | MeshBuilder::MeshBuilder(const VectorOfVectorOfPoints& v_, const bool check_orientation) : v(v_),
      | ^~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
cc1plus: all warnings being treated as errors
[5/489] Building CXX object mesh/CMakeFiles/mesh.dir/ClosingFacetComputer.cpp.o
ninja: build stopped: subcommand failed.
make: *** [Makefile:341 : build-debian] Erreur 1
sirehna@debian:~/xdyn$