:hammer: Fixed -Werror=range-loop-construct in 2DMeshDisplay.cpp
See https://github.com/Gjacquenot/test_ubuntu22/runs/6546016699?check_suite_focus=true

/opt/share/code/mesh/src/2DMeshDisplay.cpp:48:21: error: loop variable 'edge' creates a copy from type 'const std::pair<long unsigned int, long unsigned int>' [-Werror=range-loop-construct]
2436
   48 |     for (const auto edge:edges)
2437
      |                     ^~~~
2438
compilation terminated due to -Wfatal-errors.
2439
cc1plus: all warnings being treated as errors