:hammer: Fixed missing override keyword
See https://github.com/Gjacquenot/test_clang/runs/7747088752?check_suite_focus=true

[617/908] Building CXX object grpc/CMakeFiles/grpc.dir/src/GRPCForceModel.cpp.o
FAILED: grpc/CMakeFiles/grpc.dir/src/GRPCForceModel.cpp.o
/usr/bin/clang++ -DGTEST_HAS_POSIX_RE=0 -I. -I/opt/share/code/grpc/inc -I/opt/share/code/ssc -I/opt/share/code/exceptions/inc -I/opt/share/code/external_data_structures/inc -I/opt/share/code/core/inc -I/opt/share/code/environment_models/inc -I/opt/share/code/hdb_interpolators/inc -I/opt/share/code/mesh/inc -isystem /opt/eigen -isystem /opt/boost/include -isystem /opt/grpc/include -isystem grpc -isystem /opt/share/code/yaml-cpp/src -isystem /opt/share/code/yaml-cpp/include -isystem /opt/share/code/yaml-cpp/include/yaml-cpp -Werror -pedantic -pedantic-errors -Wextra -Wall -Wunused-function -Wunused-label -Wunused-parameter -Wunused-value -Wunused-variable -fno-common -Wformat=2 -Winit-self -Wpacked -Wpointer-arith -Wmissing-declarations -Wmissing-format-attribute -Wsign-compare -Wstrict-aliasing=2 -Wundef -Wconversion -Wno-misleading-indentation -Woverloaded-virtual -Weffc++ -Wwrite-strings -Wfatal-errors -Wno-deprecated -Wvariadic-macros -fPIC -std=gnu++11 -O3 -DNDEBUG -MD -MT grpc/CMakeFiles/grpc.dir/src/GRPCForceModel.cpp.o -MF grpc/CMakeFiles/grpc.dir/src/GRPCForceModel.cpp.o.d -o grpc/CMakeFiles/grpc.dir/src/GRPCForceModel.cpp.o -c /opt/share/code/grpc/src/GRPCForceModel.cpp
In file included from /opt/share/code/grpc/src/GRPCForceModel.cpp:8:
/opt/share/code/grpc/inc/GRPCForceModel.hpp:32:14: fatal error: 'extra_observations' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
        void extra_observations(Observer& observer) const;
             ^
/opt/share/code/core/inc/ForceModel.hpp:141:22: note: overridden virtual function is here
        virtual void extra_observations(Observer& observer) const;
                     ^
1 error generated.
ninja: build stopped: subcommand failed.
make: *** [Makefile:62: build-debian-clang] Error 1
Error: Process completed with exit code 2.i