:hammer: Added missing override keyword
See https://github.com/Gjacquenot/test_clang/runs/7755479888?check_suite_focus=true

[635/908] Building CXX object listeners_and_controllers/CMakeFiles/listeners_and_controllers.dir/src/listeners.cpp.o
FAILED: listeners_and_controllers/CMakeFiles/listeners_and_controllers.dir/src/listeners.cpp.o
/usr/bin/clang++ -DGTEST_HAS_POSIX_RE=0 -I. -I/opt/share/code/listeners_and_controllers/inc -I/opt/share/code/ssc -I/opt/share/code/core/inc -I/opt/share/code/exceptions/inc -I/opt/share/code/yaml_parser/inc -I/opt/share/code/environment_models/inc -I/opt/share/code/external_data_structures/inc -I/opt/share/code/mesh/inc -I/opt/share/code/hdb_interpolators/inc -I/opt/share/code/grpc/inc -isystem /opt/boost/include -isystem /opt/eigen -isystem /opt/share/code/yaml-cpp/src -isystem /opt/share/code/yaml-cpp/include -isystem /opt/share/code/yaml-cpp/include/yaml-cpp -Werror -pedantic -pedantic-errors -Wextra -Wall -Wunused-function -Wunused-label -Wunused-parameter -Wunused-value -Wunused-variable -fno-common -Wformat=2 -Winit-self -Wpacked -Wpointer-arith -Wmissing-declarations -Wmissing-format-attribute -Wsign-compare -Wstrict-aliasing=2 -Wundef -Wconversion -Wno-misleading-indentation -Woverloaded-virtual -Weffc++ -Wwrite-strings -Wfatal-errors -Wno-deprecated -Wvariadic-macros -fPIC -std=gnu++11 -std=gnu++0x -O3 -DNDEBUG -MD -MT listeners_and_controllers/CMakeFiles/listeners_and_controllers.dir/src/listeners.cpp.o -MF listeners_and_controllers/CMakeFiles/listeners_and_controllers.dir/src/listeners.cpp.o.d -o listeners_and_controllers/CMakeFiles/listeners_and_controllers.dir/src/listeners.cpp.o -c /opt/share/code/listeners_and_controllers/src/listeners.cpp
In file included from /opt/share/code/listeners_and_controllers/src/listeners.cpp:14:
/opt/share/code/listeners_and_controllers/inc/PIDController.hpp:58:14: fatal error: 'update_discrete_states' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
        void update_discrete_states(const double time, ssc::solver::ContinuousSystem& system);
             ^
/opt/share/code/listeners_and_controllers/inc/Controller.hpp:61:22: note: overridden virtual function is here
        virtual void update_discrete_states(const double time, ssc::solver::ContinuousSystem& system) = 0;
                     ^
1 error generated.