[FMI] Fixed compilation error detected on Debian 7 GCC 4.7.2 with GTEST asset ASSERT_EQ(false,...)
[  2%] Building CXX object fmi/unit_tests/CMakeFiles/fmi_tests.dir/src/ParseFMIXmlTest.cpp.o
/home/jacquenot/Work/git/SimulatorIrtJv/code/fmi/unit_tests/src/ParseFMIXmlTest.cpp: In member function ‘virtual void ParseFMIXmlTest_can_parse_real_model_variables_Test::TestBody()’:
/home/jacquenot/Work/git/SimulatorIrtJv/code/fmi/unit_tests/src/ParseFMIXmlTest.cpp:140:5: error: converting ‘false’ to pointer type for argument 1 of ‘char testing::internal::IsNullLiteralHelper(testing::internal::Secret*)’ [-Werror=conversion-null]
compilation terminated due to -Wfatal-errors.
cc1plus: all warnings being treated as errors
make[2]: *** [fmi/unit_tests/CMakeFiles/fmi_tests.dir/src/ParseFMIXmlTest.cpp.o] Erreur 1
make[1]: *** [fmi/unit_tests/CMakeFiles/fmi_tests.dir/all] Erreur 2