:hammer: Fixed -Werror=range-loop-construct in check_input_yaml.cpp
See https://github.com/Gjacquenot/test_ubuntu22/runs/6546157407?check_suite_focus=true

/opt/share/code/yaml_parser/src/check_input_yaml.cpp:75:31: error: loop variable 'commands' creates a copy from type 'const YamlTimeSeries' [-Werror=range-loop-construct]
2524
   75 |     for (const YamlTimeSeries commands : commands_input)
2525
      |                               ^~~~~~~~
2526
compilation terminated due to -Wfatal-errors.
2527
cc1plus: all warnings being treated as errors
2528