:hammer: Removed unused lambda parameter
[83/311] Building CXX object force_models/CM...e_models.dir/FastHydrostaticForceModel.cpp.o
FAILED: force_models/CMakeFiles/force_models.dir/FastHydrostaticForceModel.cpp.o
/usr/bin/clang++ -DGTEST_HAS_POSIX_RE=0 -I. -I/opt/share/code/force_models/inc -I/opt/share/code/ssc -I/opt/share/code/exceptions -I/opt/share/code/external_data_structures -I/opt/share/code/external_file_formats -I/opt/share/code/mesh -I/opt/share/code/environment_models -I/opt/share/code/yaml_parser -I/opt/share/code/hdb_interpolators -I/opt/share/code/core -isystem /opt/eigen -isystem /opt/boost/include -isystem /opt/share/code/yaml-cpp/src -isystem /opt/share/code/yaml-cpp/include -isystem /opt/share/code/yaml-cpp/include/yaml-cpp -Werror -pedantic -pedantic-errors -Wextra -Wall -Wunused-function -Wunused-label -Wunused-parameter -Wunused-value -Wunused-variable -fno-common -Wformat=2 -Winit-self -Wpacked -Wpointer-arith -Wmissing-declarations -Wmissing-format-attribute -Wsign-compare -Wstrict-aliasing=2 -Wundef -Wconversion -Wno-misleading-indentation -Woverloaded-virtual -Weffc++ -Wwrite-strings -Wfatal-errors -Wno-deprecated -Wvariadic-macros -fPIC -std=gnu++11 -O3 -DNDEBUG -std=gnu++11 -MD -MT force_models/CMakeFiles/force_models.dir/FastHydrostaticForceModel.cpp.o -MF force_models/CMakeFiles/force_models.dir/FastHydrostaticForceModel.cpp.o.d -o force_models/CMakeFiles/force_models.dir/FastHydrostaticForceModel.cpp.o -c /opt/share/code/force_models/FastHydrostaticForceModel.cpp
/opt/share/code/force_models/FastHydrostaticForceModel.cpp:65:32: fatal error: unused parameter 'that_facet_index' [-Wunused-parameter]
                  const size_t that_facet_index,
                               ^
1 error generated.